In [1]:
import numpy as np

In [2]:
vars = np.array([10 * np.random.rand(10) for _ in range(10)] + [-10 * np.random.rand(10) for _ in range(3)])

In [3]:
def rank_outliers(vars):
        variables_mean = vars.mean(axis=0)
        ranked_sol = sorted(vars, key=lambda var: np.dot(var, variables_mean))
        
        print("\n\nRANKING")
        for i, sol in enumerate(ranked_sol):
            print(f"{i}. ({np.dot(sol, variables_mean)}): {sol}")        
        
        return ranked_sol

In [4]:
rank_outliers(vars)



RANKING
0. (-151.62721923061346): [-2.22508387 -7.10705085 -3.68136057 -9.45759981 -7.72793924 -8.13388601
 -3.84063882 -8.77955844 -7.51502407 -8.53500774]
1. (-100.93261208042459): [-7.88663131 -0.8934882  -8.59694208 -0.37998965 -0.1033798  -3.74002392
 -7.40194669 -2.22416857 -7.46790063 -9.16037887]
2. (-77.1791158415061): [-1.2234804  -8.299456   -2.70484616 -3.52590803 -1.78948747 -4.73900203
 -1.42792499 -1.59100981 -3.19118685 -9.40947344]
3. (49.10105801738737): [1.00607139 0.32841571 0.70796373 1.60321374 3.00412162 6.17175799
 0.06687772 0.45459025 6.21204808 0.13800452]
4. (94.85669299113209): [2.36457356 5.37631657 2.42474077 1.98726851 1.52991532 5.89124641
 3.8532474  8.14377499 4.51172785 7.01670026]
5. (98.19852430080425): [0.16625192 4.69260748 7.8318061  7.19902785 0.77861916 4.61435314
 4.90751891 3.18168823 4.50149142 4.62739517]
6. (100.6747087791629): [5.90909383 7.16826199 0.42123    6.16278326 1.86337403 9.37761302
 1.7223316  3.23162573 2.55224428 0.1568153

[array([-2.22508387, -7.10705085, -3.68136057, -9.45759981, -7.72793924,
        -8.13388601, -3.84063882, -8.77955844, -7.51502407, -8.53500774]),
 array([-7.88663131, -0.8934882 , -8.59694208, -0.37998965, -0.1033798 ,
        -3.74002392, -7.40194669, -2.22416857, -7.46790063, -9.16037887]),
 array([-1.2234804 , -8.299456  , -2.70484616, -3.52590803, -1.78948747,
        -4.73900203, -1.42792499, -1.59100981, -3.19118685, -9.40947344]),
 array([1.00607139, 0.32841571, 0.70796373, 1.60321374, 3.00412162,
        6.17175799, 0.06687772, 0.45459025, 6.21204808, 0.13800452]),
 array([2.36457356, 5.37631657, 2.42474077, 1.98726851, 1.52991532,
        5.89124641, 3.8532474 , 8.14377499, 4.51172785, 7.01670026]),
 array([0.16625192, 4.69260748, 7.8318061 , 7.19902785, 0.77861916,
        4.61435314, 4.90751891, 3.18168823, 4.50149142, 4.62739517]),
 array([5.90909383, 7.16826199, 0.42123   , 6.16278326, 1.86337403,
        9.37761302, 1.7223316 , 3.23162573, 2.55224428, 0.15681537]),
 arr